services:
  splunk-go-sdk-test:
    image: splunk/splunk:9.1
    build: .
    cpu_count : 1
    ports:
      - "8000:8000"
      - "8089:8089"
      - "8088:8088"
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: splunked
    volumes:
      - .:/code
