#FROM --platform=${BUILDPLATFORM} golang:1.16-rc AS build
FROM golang:1.16-rc AS build
WORKDIR /src
#ENV CGO_ENABLED=0
COPY examples/hello examples/hello
COPY modinputs modinputs
COPY go.mod .
ARG GOOS
ARG GOARCH
# for gitlab private repos, authentication with tokens is necessary 
# and GOPRIVATE must skip verification for private git server
# RUN echo "machine gitserver.company.com login go-build password SOME-TOKEN" > ~/.netrc
# ENV GOPRIVATE=gitserver.company.com/*
WORKDIR /src/examples/hello
RUN go mod tidy
RUN GOOS=${GOOS} GOARCH=${GOARCH} go build -o /out/example main.go

FROM scratch as bin
COPY --from=build /out/ /
COPY --from=build /src/examples/hello/sampleconfig.xml /
WORKDIR /
ENTRYPOINT ["/example"]

#FROM scratch AS bin-windows
#COPY --from=build /out/example /example.exe

